---
title: "Environmental Distance_Herb to EOR"
author: "Michelle DePrenger-Levin"
date: "October 11, 2018"
output: html_document
---

```{r}
library(adegenet)
library(pegas)
library(strataG)

load("Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/Data/pca_data2.Rda")


```

Reference stackmini to have same environmental variables in PCA as in the maxent models
```{r}

animatepca_data <- Map(data.frame, pca_data2, SpeciesID=as.list(seq(1,length(pca_data2),1)))

pca_all <- lapply(1:length(pca_data2), function(i){
  x <- animatepca_data[[i]]
  x.pca <- princomp(~WinterPrecip+SummerPrecip+WinterMinTemp+WinterMaxTemp+FallMaxTemp, 
                    data = x[,c("WinterPrecip","SummerPrecip","WinterMinTemp","WinterMaxTemp","FallMaxTemp")], 
                    na.action = na.omit, cor=TRUE)
  # x.load <- loadings(x.pca)
  x.pc1 <- predict(x.pca)
  x.pc <- data.frame(x.pc1,x[!is.na(x$WinterMaxTemp),]) #x$pa where 1=EOR presence, 3=EOR background; 2=Herb presence, 4=herb background
  x.PoV <- x.pca$sdev^2/sum(x.pca$sdev^2) #Percent of variance explained by the components
  out <- data.frame(x.pc,PoV1=x.PoV[1],PoV2=x.PoV[2])
  out
})

anim_all <- do.call(rbind, pca_all)
table(anim_all$PoV1)
```

```{r}
animatePCA <- list()
for(i in 1:46){
  animatePCA[[i]] <- ggplot(anim_all[anim_all$SpeciesID == i,], aes(Comp.1, Comp.2, 
                                 colour=as.factor(pa), 
                                 shape=as.factor(pa),
                                 frame=SpeciesID))+
    ggtitle(anim_all$GNAME[anim_all$SpeciesID == i][1])+
    geom_point()+
                    stat_ellipse()+
                    theme_bw()+
                    xlab(paste("PC1 (",round(anim_all$PoV1[anim_all$SpeciesID == i][1],2)*100,"%)",sep=""))+
                    ylab(paste("PC2 (",round(anim_all$PoV2[anim_all$SpeciesID == i][2],2)*100,"%)",sep=""))+
                    theme(plot.title=element_text(hjust=0))+
                    theme(legend.justification=c(0,1), legend.position=c(0,1),
                          legend.background = element_rect(fill=alpha('white', 0.1)))+
                    #labs(color = "Presence/Background", shape = "Presence/Background")+
    scale_shape_manual(name = "Presence/Background", 
                       labels=c("EOR presence",
                              "Herbarium presence",
                              "EOR background",
                              "Herbarium background"),
                       values=c(16,17,1,2)) +               
    scale_colour_manual(name = "Presence/Background",
                       labels=c("EOR presence",
                              "Herbarium presence",
                              "EOR background",
                              "Herbarium background"),
                       values=c("indianred4","hotpink3","lightslategray","lightsteelblue3")) #("darkolivegreen4","green4","lightgrey","ivory4"))
}

for(i in 1:46){
  print(animatePCA[[i]])
}
```