---
title: "Sampling impacts on SDM"
author: "Michelle DePrenger-Levin"
date: "2/15/2020"
output: html_document
---

```{r}
# install.packages("installr")
# require(installr)
# updateR()

# maybe a mix of R3.5.X and R3.6.X so need to update everything?
# update.packages(ask = FALSE, checkBuilt = TRUE)

# maybe broken and not getting updated or removed, need to find and delete
# find.package("knitr")
# remove.packages("knitr")
# 
# install.packages("rJava")

library(diagram)

require(DiagrammeR)

# simmulations
library(virtualspecies)

# SDM
library(rJava)
library(dismo)

# Mapping
library(rgeos)
library(raster)
library(maptools)
library(dismo)
library(RNRCS)
library(rgdal)


# Parallelization
library(foreach)
library(parallel)
library(doParallel)
library(magrittr) # pipe %>%


thin.max <- function(x, cols, npoints){
  #Create empty vector for output
  inds <- vector(mode="numeric")
  
  #Create distance matrix
  this.dist <- as.matrix(dist(x[,cols], upper=TRUE))
  
  #Draw first index at random
  inds <- c(inds, as.integer(runif(1, 1, length(this.dist[,1]))))
  
  #Get second index from maximally distant point from first one
  #Necessary because apply needs at least two columns or it'll barf
  #in the next bit
  inds <- c(inds, which.max(this.dist[,inds]))
  
  while(length(inds) < npoints){
    #For each point, find its distance to the closest point that's already been selected
    min.dists <- apply(this.dist[,inds], 1, min)
    
    #Select the point that is furthest from everything we've already selected
    this.ind <- which.max(min.dists)
    
    #Get rid of ties, if they exist
    if(length(this.ind) > 1){
      print("Breaking tie...")
      this.ind <- this.ind[1]
    }
    inds <- c(inds, this.ind)
  }
  
  return(x[inds,])
}
```
diagram
```{r}

m <- matrix(nrow=6, ncol = 6, byrow = TRUE, data = c(
  # P  f  s  g  dd  sz  c  m
   0, 0, 0, 0, 0, 0, 0, 0,0, 
   1, 0, 0, 0, 0, 0, 0, 0,0, 
   0, 2, 0, 0, 0, 0, 0, 0,0, 
   0, 0, 3, 0, 0, 0, 0, 0,0, 
   0, 0, 0, 4, 0, 0, 0, 0,0, 
   0, 5, 6, 5, 0, 0, 0, 0,0, 
   0, 8, 9,10, 0, 0, 0, 0,0, 
   0,11,12,13, 0, 0, 0, 0,0
   )) 
names <- c("Model Organism", "Climate Drivers", "'True' distribution", "sample", "SDMs",
           "Compare to 'True'")

# m[2,1] <- m[3,1] <- m[4,1] <- m[5,1] <- m[6,2] <- m[6,3] <- m[6,4] <- 
#   m[7,2] <- m[7,3] <- m[7,4] <- 
#   m[8,2] <- m[8,3] <- m[8,4] <- "lm" 
plotmat(m, pos = c(1, 1,1,1,1,1), curve = 0, name = names, 
        box.type = "square", cex.txt = 0.45, box.prop = 0.3,
        arr.type = "triangle", arr.pos = 0.5, prefix = "m")


```

DiagrammeR 
```{r}
# Erysimum capitatum or Rhodiola integrifolium or Hymenoxys grandiflora

grViz("digraph flowchart {
      # node definitions with substituted label text
      node [fontname = Helvetica, shape = rectangle]        
      tab1 [label = '@@1']
      tab2 [label = '@@2']
      tab3 [label = '@@3']
      tab4 [label = '@@4']
      tab5 [label = '@@5']
      tab6 [label = '@@6']
      tab7 [label = '@@7']
      tab8 [label = '@@8-1']
      tab9 [label = '@@8-2']
      tab10 [label = '@@8-3']
      tab11 [label = '@@8-4']
      
      # edge definitions with the node IDs
      tab1 -> tab3 -> tab4;
      tab4 -> tab8;
      tab4 -> tab9;
      tab4 -> tab10;
      tab4 -> tab11;
      tab2 -> tab3;
      tab5 -> tab6;
      tab8 -> tab5;
      tab9 -> tab5;
      tab10 -> tab5;
      tab11 -> tab5;
      tab5 -> tab6;
      tab5 -> tab6;
      tab5 -> tab6;
      tab5 -> tab6;
      tab7 -> tab2;
      }

      [1]: 'Model organism (Claytonia rubra)'
      [2]: 'Climate Drivers'
      [3]: 'Build true distribution'
      [4]: 'sample'
      [5]: 'SDM'
      [6]: 'Compare with True'
      [7]: 'snow melt, min and max temp, soil moisture, dummy'
      [8]: c('Ad Hoc','Adaptive cluster sampling','Neutral sampling','Random')
      ")


```


Bayesian model to treat amount of the niche sampled as a latent vairable  
```{r}
# tab3 ->