---
title: "SDM_Herbtrain_EORtest"
author: "Michelle DePrenger-Levin"
date: "November 3, 2018"
output: html_document
---

```{r}
rm(list=ls())
library(ENMeval)
library(maptools)
library(sp)
library(rgeos)
library(spdep)
library(rgdal)
library(maptools)
library(raster)
library(dismo)

load("Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/Data/Maxentspecies.Rda")

load("Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/Data/distXsp1.Rda")
colocounties <- readOGR(dsn="Q:/Research/All_Projects_by_Species/aa_Shapefiles_Maps/aa_GENERAL_non-species_files/All_General_Background_Layers/Colorado/CO_Counties", layer="counties_wgs84")

load("Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/Data/pca_data4.Rda")

```



```{r}
coElev <- raster("Q:/Research/All_Projects_by_Species/aa_Shapefiles_Maps/aa_GENERAL_non-species_files/All_General_Background_Layers/Colorado/Elevation_VT/CO_Mosaic_Elevation_VT/co_elev_VT_WGS84.tif")
coAspect <- raster("Q:/Research/All_Projects_by_Species/aa_Shapefiles_Maps/aa_GENERAL_non-species_files/All_General_Background_Layers/Colorado/Aspect_VT/co_aspect_VT_WGS84.tif")
coSlope <- raster("Q:/Research/All_Projects_by_Species/aa_Shapefiles_Maps/aa_GENERAL_non-species_files/All_General_Background_Layers/Colorado/Slope_VT/co_slope_VT_WGS84.tif")

rasterstack_2 <- stack(list(coElev, coAspect, coSlope))
rscrs_2 <- rasterstack_2@crs@projargs # "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
```



```{r}
 i<-pca_data4[[2]]

#Loop through all the species
MaxentspeciesEORandHerb <- lapply(pca_data4, function(i){
  
  # Only want records after 1980
  #background points don't have lastobs
  x <- i
  x <- x[!grepl("-99",x$Lastobs),]
  x <- x[x$Lastobs!="",]
  x <- x[(as.Date(x$Lastobs)>"1980-12-31"),]
  
  checksp <- sapply(split(x, x$pa), function(y) nrow(y))
  
    if(sum(checksp<12)>0){
      NULL
      } else {
        
        for(l in 1:10){
          speciestable <- x
          kfoldnum<-4
          speciestable <- speciestable[!is.na(speciestable$pa),]
          speciestable$group_pa <- unlist(lapply(split(speciestable, speciestable$pa), function(xsp){
            kfold(xsp$pa, kfoldnum)
          }))
          
          test <- sample(1:4, 1)
          # Hold out a little bit that is used to test (25%), keep the rest to train (75%)
          train_pHerb <- speciestable[speciestable$pa == 2 & speciestable$group_pa != test, c("x1","x2")]
          train_pEOR <- speciestable[speciestable$pa == 1 & speciestable$group_pa != test, c("x1","x2")]
          train_bHerb <- speciestable[speciestable$pa == 4 & speciestable$group_pa != test, c("x1","x2")]
          train_bEOR <- speciestable[speciestable$pa == 3 & speciestable$group_pa != test, c("x1","x2")]
          
          test_pHerb <- speciestable[speciestable$pa == 2 & speciestable$group_pa == test, c("x1","x2")]
          test_pEOR <- speciestable[speciestable$pa == 1 & speciestable$group_pa == test, c("x1","x2")]
          test_bHerb <- speciestable[speciestable$pa == 4 & speciestable$group_pa == test, c("x1","x2")]
          test_bEOR <- speciestable[speciestable$pa == 3 & speciestable$group_pa == test, c("x1","x2")] 
          
          meEOR <- maxent(rasterstack_2, p=train_pEOR, a=train_bEOR,
                          path = paste("Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/RMaxEnt/", unique(i$GNAME)[1],"_EOR2",sep=""))
          meHerb <- maxent(rasterstack_2, p=train_pHerb, a=train_bHerb,
                          path = paste("Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/RMaxEnt/", unique(i$GNAME)[1],"_herb2",sep=""))
          
          #evalidate the model
          eEOR <- dismo::evaluate(test_pEOR, test_bEOR, meEOR, rasterstack_2)
          gc()
          
          eHerb <- dismo::evaluate(test_pHerb, test_bHerb, meHerb, rasterstack_2)
          gc()
              
          #Visulatize predictions
          writeRaster(dismo::predict(meHerb,rasterstack_2),
                      paste("Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/RMaxEnt/HerbOnly2_",unique(i$GNAME)[1],l,".tif", sep=""),overwrite=TRUE)
          gc()
          writeRaster(dismo::predict(meEOR, rasterstack_2),paste("Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/RMaxEnt/EOROnly2_",unique(i$GNAME)[1],l,".tif", sep=""),overwrite=TRUE)
          gc()
          
          thresEOR <- dismo::threshold(eEOR) 
          thresHerb <- dismo::threshold(eHerb)

          out <- list(unique(i$GNAME)[1],
                      meEOR,eEOR,thresEOR,eEOR@auc,
                      meHerb,eHerb,thresHerb,eHerb@auc)
          out
        
        }
        

           
  
        }
  })
  

save(MaxentspeciesEORandHerb, file= "Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/Data/MaxentspeciesEORandHerb.Rda")

```



```{r}
Maxentspecies[[1]]

outputs <- mapply( '[[',Maxentspecies, 2)
names <- mapply('[[', Maxentspecies, 6)
auc_max <- mapply('[[', Maxentspecies, 4)

length(names)
outputs[[1]]

# HERE ARE VALUES! AUC 
AUCtable <- data.frame(Sp=unlist(names),AUC=unlist(auc_max))


# Average distance by species DIST
namesdistXsp <- mapply('[[',distXsp, 1)

# namesdistXsp <- 
  unlist(lapply(, function(x) unique(namesdistXsp[[x]]@data$scientificName)))
DISTtable <- data.frame(Sp=)


maxentposition <- mapply(function(x,y) x %in% y,
                         lapply(1:60, function(i){
                           c(g1g2names$AcceptedName[i],g1g2names$Taxon[i])
                           }),
                         mapply(FUN=function(x) x[[6]],Maxentspecies))

MEpos <- apply(maxentposition,2, function(x) sum(x) )


# 
# which(MEpos>0)
# length(which(MEpos>0)) #28

MEposition <- match(1:60,which(MEpos>0))
mepo <- which(!is.na(MEposition))

length(maxentposition[!is.na(maxentposition)]) #missing first one... need both names

aucs <- lapply(which(!sapply(outputs,is.null)), function(x) outputs[[x]]@auc)
length(aucs)
names[!sapply(names,is.null)]

hist(unlist(aucs),breaks=5)

```


```{r}
table1 <- lapply(1:60, function(i){
  checkrecords <- pca_herb_SAE[[herbposition[i]]]
  if(is.null(checkrecords)){
    NULL
  } else {
    checkrecords <- checkrecords[checkrecords$Lastobs!="",]
    checkrecords <- checkrecords[!grepl("-99",checkrecords$Lastobs),]
    checkrecords$Lastobs <- as.Date(checkrecords$Lastobs)
    checkrecords <- checkrecords[!is.na(checkrecords$Lastobs),]
      x <- checkrecords
      x <- x[(as.Date(x$Lastobs)>"1980-12-31"),]
      
      data.frame(Species=g1g2names$AcceptedName[i],
        EarlyYrAll = min(as.Date(checkrecords$Lastobs)),
        LateYrAll=max(as.Date(checkrecords$Lastobs)),N=nrow(checkrecords),
                 EarlyYr=min(as.Date(x$Lastobs)),LateYr=max(as.Date(x$Lastobs)),Nsmd=nrow(x))
  }})

write.table(do.call(rbind,table1), "clipboard", sep="\t", row.names = FALSE)
```

```{r}
distXsp[[1]][[1]]

write.table(do.call(rbind,lapply(which(!is.na(herbposition)), function(x){
  data.frame(Species=unique(distXsp[[x]][[1]]$scientificName)[1],
             Area=(sum(distXsp[[x]][[3]]))/1000)
})), "clipboard", sep="\t", row.names=FALSE)

```


```{r}

lapply(1:length(Maxentspecies))
Maxentspecies[[1]][[2]]@auc

# which(!is.na(herbposition))

MEposition2 <- which(MEpos>0)

do.call(rbind,lapply(MEposition2, function(x){
  # if(sum(!is.na(MEposition[x]) & !is.na(herbposition[x]))>0){
    data.frame(Species=unique(Maxentspecies[[x]]$GNAME)[1],
             Area=(sum(distXsp[[backeorposition[x]]][[3]]))/1000,
             AUC=Maxentspecies[[x]][[2]]@auc)
  # } else {
    # data.frame(Species=unique(distXsp[[x]][[1]]$scientificName)[1],
    #            Area=(sum(distXsp[[x]][[3]]))/1000,
    #            AUC=NA)
  # }
  }))



```


