---
title: "SDM_Herbtrain_EORtest"
author: "Michelle DePrenger-Levin"
date: "November 3, 2018"
output: html_document
---

```{r}
library(ENMeval)
library(maptools)
library(sp)
library(rgeos)
library(spdep)
library(rgdal)
library(maptools)
library(raster)
library(dismo)
```

```{r}
load("Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/Data/pca_eor_SAE.Rda") 
load("Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/Data/pca_eorandherb_SAE.Rda") 
load("Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/Data/pca_herb_SAE.Rda")
load("P:/hackathon/Simulations/envs.backgHerb_SAE.Rda")
load("Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/Data/bg.herb.Rda")
load("Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/Data/backgroundEORs.Rda") 


```


```{r}
coElev <- raster("Q:/Research/All_Projects_by_Species/aa_Shapefiles_Maps/aa_GENERAL_non-species_files/All_General_Background_Layers/Colorado/Elevation_VT/CO_Mosaic_Elevation_VT/co_elev_VT_WGS84.tif")
coAspect <- raster("Q:/Research/All_Projects_by_Species/aa_Shapefiles_Maps/aa_GENERAL_non-species_files/All_General_Background_Layers/Colorado/Aspect_VT/co_aspect_VT_WGS84.tif")
coSlope <- raster("Q:/Research/All_Projects_by_Species/aa_Shapefiles_Maps/aa_GENERAL_non-species_files/All_General_Background_Layers/Colorado/Slope_VT/co_slope_VT_WGS84.tif")

rasterstack_2 <- stack(list(coElev, coAspect, coSlope))
rscrs_2 <- rasterstack_2@crs@projargs # "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
```


```{r}
# load( "Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/Data/pca_eorandherb_SAE.Rda" )
load("Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/Data/distXsp1.Rda")
# load("Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/Data/pca_herb_SAE.Rda")
# load("P:/hackathon/Simulations/envs.backgEOR.Rda")
# load("P:/hackathon/Simulations/envs.backgHerb.Rda")
# load("P:/hackathon/Simulations/circleHerb.Rda")
# load("Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/Data/bg.herb.Rda")
load("Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/Data/g1g2names.Rda")


want <- which(!is.na(mapply('[[', distXsp, 1)))
wantEOR <- which(!is.na(mapply('[[', distXsp, 4)))

l1eor <- readShapePoly("Q:/Research/All_Projects_by_Species/aa_Shapefiles_Maps/aa_ArcMap_Projects/Link_EO_Herbarium_Records/L1shp")
proj4string(l1eor) <- CRS("+proj=utm +zone=13 +datum=NAD83 +units=m +no_defs +ellps=GRS80 +towgs84=0,0,0")
l1G1G2 <- disaggregate(l1eor[l1eor$GRANK %in% c("G1","G2"),])
l1G1G2$PolyID <- do.call(rbind, lapply(split(l1G1G2,l1G1G2$OBJECTID),
                                       function(x){
              x$POlyID <- paste(x$EO_ID, LETTERS[seq(from=1, to= nrow(x))],sep="")
              x
              }))

polys <- lapply(1:nrow(g1g2names), function(i){
     polys <- l1G1G2[l1G1G2$GNAME %in% c(g1g2names$AcceptedName[i],
                                         g1g2names$Taxon[i]),]
     # polys <- spTransform(polys, CRS("+proj=utm +zone=13 +datum=NAD83 +units=m +no_defs +ellps=GRS80 +towgs84=0,0,0"))
     polys
     })


# Error in prettyNum(.Internal(format(x, trim, digits, nsmall, width, 3L, : first argument must be atomic
# Can't call polys@data[as.Date...] have to do polys[as.Date...]
polys_post1980 <- lapply(1:60, function(i){
     polys <- l1G1G2[l1G1G2$GNAME %in% c(g1g2names$AcceptedName[i],
                                         g1g2names$Taxon[i]),]
     # polys <- spTransform(polys, CRS("+proj=utm +zone=13 +datum=NAD83 +units=m +no_defs +ellps=GRS80 +towgs84=0,0,0"))
     polys@data$LASTOBS <- as.Date(polys@data$LASTOBS, format="%Y-%m-%d")
     out <- polys[(!is.na(polys@data$LASTOBS) & polys@data$LASTOBS >"1980-12-31"),]
     out
     })

plot(polys_post1980[[4]])

```


```{r}
herbpoints <- list()
eorpoints <- list()

EORgridpoints <- mapply('[[', distXsp, 4)
Herboints <- mapply('[[', distXsp, 1)
length(EORgridpoints[!is.na(EORgridpoints)])
length(wantEOR)

colocounties <- readOGR(dsn="Q:/Research/All_Projects_by_Species/aa_Shapefiles_Maps/aa_GENERAL_non-species_files/All_General_Background_Layers/Colorado/CO_Counties", layer="counties_wgs84")
colocounties.UTM <- readOGR(dsn="Q:/Research/All_Projects_by_Species/aa_Shapefiles_Maps/aa_GENERAL_non-species_files/All_General_Background_Layers/Colorado/CO_Counties", layer="counties")

which(is.na(EORgridpoints))
identical(which(!is.na(Herboints)),want)
wantboth <- want[!is.na(wantEOR)]
unique(Herboints[[1]]@data$scientificName)[1]

for(i in 1:length(want[want!=41])){
    herbpoints[[i]] <- spTransform((distXsp[[want[i]]][[1]]), CRS("+proj=utm +zone=13 +datum=NAD83 +units=m +no_defs +ellps=GRS80 +towgs84=0,0,0"))
    eorpoints[[i]] <- spTransform(distXsp[[want[i]]][[4]], CRS("+proj=utm +zone=13 +datum=NAD83 +units=m +no_defs +ellps=GRS80 +towgs84=0,0,0"))
    plot(colocounties.UTM, main=paste(unique(herbpoints[[i]]@data$scientificName)[1]))
    plot(herbpoints[[i]], add=TRUE, col="blue", pch=16)
    plot(eorpoints[[i]], add=TRUE)
    plot(polys_post1980[[want[i]]], add=TRUE, border="red", lwd=4)
}
```


# Already loaded, skip!
```{r, eval=FALSE}

pca_eor_SAE <- lapply(polys_post1980, function(pol){
  areanow <- sapply(slot(pol, "polygons"), 
                        slot, "area")
  grid <- lapply(1:length(pol), function(x){
    gridout <- makegrid(pol[x,], cellsize=50, pretty=FALSE)
    gridout <- SpatialPointsDataFrame(gridout, data.frame(id=1:nrow(gridout),
                                                       polyid=x,
                                                       pol@data$PolyID@data[x,],
                                                       area = sapply(slot(pol[x,],"polygons"), slot, "area")),
                                      proj4string = CRS(proj4string(pol[x,])))
     out <- gridout[pol[x,],]
     if(nrow(out@data)==0){
       center <- gCentroid(pol[x,])
       centerout <- SpatialPointsDataFrame(center, data.frame(id=1,
                                                       polyid=x,
                                                       pol@data$PolyID@data[x,],
                                                       area = sapply(slot(pol[x,],"polygons"), slot, "area")),
                                      proj4string = CRS(proj4string(pol[x,])))
       centerout
     } else {
       out
     }
  })
  mergedEORs <- do.call(rbind,grid)
  mergedEORs <- spTransform(mergedEORs, CRS(paste(rscrs_2)))
  data_eor <- data.frame(coordinates(mergedEORs), id= mergedEORs$id, polyid = mergedEORs$polyid,
                          Bestcrs=mergedEORs$BESTSRC, firstobs=mergedEORs$FIRSTOBS, 
                            GRANK=mergedEORs$GRANK,
                            GNAME=mergedEORs$GNAME,ENDEMIC=mergedEORs$ENDEMIC, 
                            Lastobs=mergedEORs$LASTOBS,dist=NA,area=sum(areanow),
                            extract(rasterstack_2, mergedEORs))
  data_eor
})

save(pca_eor_SAE, file= "Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/Data/pca_eor_SAE.Rda") 

(pca_eor_SAE[[1]])
(mapply(FUN=function(x) unique(x$GNAME),pca_eor_SAE))
plot(pca_eor_SAE[[41]][,c('x1','x2')])
```


```{r}
pca_eorandherb_SAE <- lapply(1:nrow(g1g2names), function(sp){
  #put grid points across colorado, sample from it for each polygons
     polys <- l1G1G2[l1G1G2$GNAME %in% c(g1g2names$AcceptedName[sp],
                                         g1g2names$Taxon[sp]),] 
      #area of each polygon
      areanow <- sapply(slot(l1G1G2[l1G1G2$GNAME %in% c(g1g2names$AcceptedName[i],
                                             g1g2names$Taxon[i]),], "polygons"), 
                        slot, "area")

     cellsize <- 100
     grid <- lapply(1:length(polys), function(i){
       if(sqrt((polys[i,]@bbox[3]-polys[i,]@bbox[1])*(polys[i,]@bbox[4]-polys[i,]@bbox[2]))/cellsize < 1){
         grid <- makegrid(polys[i,], cellsize = 10, pretty=FALSE) #0.1km
         gridout <- SpatialPointsDataFrame(grid, data.frame(id=1:nrow(grid),polyid=i,
                                                            polys@data$PolyID@data[i,]),
                                             proj4string = CRS(proj4string(polys[i,])))
           gridout
         } else {
           grid <- makegrid(polys[i,], cellsize = cellsize, pretty=FALSE) #1km 
           gridout <- SpatialPointsDataFrame(grid, data.frame(id=1:nrow(grid),polyid=i,
                                                              polys@data$PolyID@data[i,]),
                                             proj4string = CRS(proj4string(polys[i,])))
           gridout
           }
       })
     

     ov <- lapply(1:length(polys), function(i){
         out <- grid[[i]][polys[i,],]
         out
         })

     eor_data <- lapply(1:length(ov), function(x){
       if(nrow(ov[[x]]@data)==0){
         center <- gCentroid(polys[i,])
         centerout <- SpatialPointsDataFrame(center, data.frame(id=1,polyid=x,
                                                                polys@data$PolyID@data[i,]),
                                             proj4string = CRS(proj4string(polys[i,])))
         out <- spTransform(centerout, CRS(paste(rscrs_2)))
         out
       } else {
         out <- spTransform(ov[[x]], CRS(paste(rscrs_2)))
         out
       }
     })
     
     mergedEORs <- do.call(rbind,eor_data)
     data_eor <- data.frame(coordinates(mergedEORs),id=mergedEORs$id,polyid=mergedEORs$polyid,
                            Bestcrs=mergedEORs$BESTSRC, firstobs=mergedEORs$FIRSTOBS, 
                            GRANK=mergedEORs$GRANK,
                            GNAME=mergedEORs$GNAME,ENDEMIC=mergedEORs$ENDEMIC, 
                            Lastobs=mergedEORs$LASTOBS,dist=NA,area=sum(areanow),
                            extract(rasterstack_2, mergedEORs))
     data_eor
})

 save(pca_eorandherb_SAE, file= "Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/Data/pca_eorandherb_SAE.Rda") 

#More points! 
 (pca_eorandherb_SAE[[1]])
(mapply(FUN=function(x) unique(x$GNAME),pca_eorandherb_SAE))
plot(pca_eorandherb_SAE[[41]][,c('x1','x2')])
```

pca_herb_SAE
[[41]]
[1] Ptilagrostis porteri
Levels: Ptilagrostis porteri

pca_eorandherb_SAE
41: Packera mancosana
54: Ptilagrostis porteri
```{r}
distXsp1_pca <- do.call(c,mapply('[[', distXsp, 1))
distXsp1_pca <- distXsp1_pca[want]
#distXsp1_pca <- distXsp1_pca[!is.na(distXsp1_pca)]
pca_herb_SAE <- lapply(distXsp1_pca, function(x){
#  transdf <- data.frame(distXsp[[x]][[1]],dist=distXsp[[x]][[2]],area=distXsp[[x]][[3]])
  out <- spTransform(x, CRS(paste(rscrs_2)))
  pca_herbout <- data.frame(coordinates(out),id=out$id,polyid=NA,
                            Bestcrs=out$institutionCode, firstobs=out$eventDate, 
                            GRANK=NA,
                            GNAME=out$scientificName,ENDEMIC=NA, 
                            Lastobs=out$eventDate,dist=out$dist,area=out$area,
                            extract(rasterstack_2, out))
  pca_herbout
})
save(pca_herb_SAE, file= "Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/Data/pca_herb_SAE.Rda")

 (pca_herb_SAE[[1]])
(mapply(FUN=function(x) unique(x$GNAME)[1],pca_herb_SAE))
(mapply(FUN=function(x) unique(x$GNAME),pca_eorandherb_SAE))

# Which position of herb matches in eorandherb (and either NA or the spot it matches)
herbpoisition <- match(mapply(FUN=function(x) unique(x$GNAME),pca_eorandherb_SAE),mapply(FUN=function(x) unique(x$GNAME)[1],pca_herb_SAE))

length(herbpoisition) #60
# 1:60 for EOR and the associated herb one

# Which poistion of eorandherb matches where in herb (and either NA or the spot it matches)
match(mapply(FUN=function(x) unique(x$GNAME)[1],pca_herb_SAE),mapply(FUN=function(x) unique(x$GNAME),pca_eorandherb_SAE))

#to match by species, select the number 1:60 for EOR and herbposition[#] for herb
plot(pca_herb_SAE[[herbpoisition[54]]][,c(1:2)])
points(pca_eorandherb_SAE[[54]][,c('x1','x2')], col="red", pch=16)

```

```{r}

herbGnames <- lapply(pca_herb_SAE, function(x){
  unique(x$GNAME)
})

eorGnames <- lapply(pca_eorandherb_SAE, function(x){
  unique(x$GNAME)
})

eorGnames[want];herbGnames
```

```{r}

#Get backgrounds for each species according to the herbarium specimens

envs.backg.herb_SAE <- list()
for(i in 1:length(want)){
  envs.backg.herb_SAE[[i]] <- crop(rasterstack_2, circleHerb[[i]]@polygons)
}

for(i in 1:length(want)){
  envs.backg.herb_SAE[[i]] <- mask(envs.backg.herb_SAE[[i]], circleHerb[[i]]@polygons)
}


save(envs.backg.herb_SAE, file= "P:/hackathon/Simulations/envs.backgHerb_SAE.Rda")

pointsXsp.latlon <- list()
for(i in 1:length(want)){
  pointsXsp.latlon[[i]] <- spTransform(distXsp[[want[1]]][[1]], CRS(rscrs_2))
}

bg.herb_SAE <- lapply(1:length(want), function(i){
  background <- as.data.frame(randomPoints(envs.backg.herb[[i]][[1]], n=nrow(pointsXsp.latlon[[i]]@coords)+
                                          0.25*(nrow(pointsXsp.latlon[[i]]@coords))))
  out <- data.frame(x1 = background$x, x2 = background$y, id = NA, polyid=NA, Bestcrs=NA, firstobs=NA,
                           GRANK=NA, GNAME=g1g2names$AcceptedName[i],ENDEMIC=NA, Lastobs=NA,
                    dist=NA,area=NA,
                    raster::extract(rasterstack_2, background))
  out
})
save(bg.herb_SAE, file= "Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/Data/bg.herb.Rda")

#just make some random background points for EORs
bg.EORs <- lapply(EORsxsp[!is.na(EORsxsp)], function(x){
  out <- randomPoints(x, n=row(x@coords)+0.25*(nrow(x@coords)))
  out
})

#make new circles
circleEORs <- list()
for(i in 1:length(want)){
  circleEORs[[i]] <- circles(pca_eor_SAE[[i]][,c("x1","x2")], d=50000, lonlat=TRUE) #50 km radius circles
}

pol <- lapply(circleEORs, function(x){
  out <- polygons(x)
  proj4string(out) <- CRS(rscrs_2)
  out
  })

# RasterLayer from explainatory variables
# mask <- coElev
bg_rspatial <- randomPoints(coElev, 5000)
plot(bg_rspatial) #5000 points across Colorado. 

# put random points in the circle mask
extent(pol[[1]]) # but this will be a square, not a circle, need to repeat the over where I get the subset of bg points that fall in the circles bg[circle[i,],] (assuming there are more than one circle)
bg_rspatialincircle <- randomPoints(coElev, 50, ext=extent(pol[[1]]))

#make into spatialpoints
bg_sp <- data.frame(bg_rspatialincircle)
coordinates(bg_sp) <- ~ x+y
proj4string(bg_sp) <- CRS(rscrs_2)

proj4string(pol[[1]])

plot(colocounties)
points(bg_rspatialincircle)
plot(pol[[1]], add=TRUE)
points(bg_sp[pol[[1]],], col="red")

# Don't think I need to do this, get points outside circles
  # # unique cells, numbered top to bottom, left to right
  # cells <- cellFromXY(coElev, backgnd)
  # cells <- unique(cells)
  # xy <- xyFromCell(coElev, cells)
  # plot(pol[[1]])
  # points(xy)


# http://rspatial.org/sdm/rst/3_sdm_absence-background.html 
backgroundEORs <- lapply(pol, function(x){
  backgnd <- randomPoints(coElev, 300, ext=extent(x))
  bg <- data.frame(backgnd)
  coordinates(bg) <- ~x+y
  proj4string(bg) <- CRS(rscrs_2)
  bg <- bg[x,] #only points that fall within circles
  out <- data.frame(x1 = bg@coords[,1], x2 = bg@coords[,2], id = 1:nrow(bg@coords), 
                    polyid=NA, Bestcrs=NA, firstobs=NA,
                    GRANK=NA, GNAME=g1g2names$AcceptedName[i], ENDEMIC=NA, Lastobs=NA,
                    dist=NA,area=NA,
                    raster::extract(rasterstack_2, bg))
  out
  })
save(backgroundEORs, file= "Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/Data/backgroundEORs.Rda") 

backgroundEORs[[1]]
```


```{r}
#Loop through all the species
Maxentspecies <- lapply(1:length(want), function(i){
  checkrecords <- pca_herb_SAE[[i]]

  # to keep at least 5 records per group
  if(nrow(checkrecords)<4){
    NULL
  } else {
        speciestab <- pca_herb_SAE[[i]]
        speciestab$pa <- 1
        eortab <- pca_eorandherb_SAE[[want[i]]]
        eortab$pa <- 2

      out <- list()
      for(l in 1:10){    
          train_pHerb <- speciestab[,c("x1","x2")]
          train_bHerb <- bg.herb_SAE[[i]]
          
          test_pEOR <- speciestable[speciestable$pa == 1 & speciestable$group_pa==test,c("x1","x2")]
          
          me <- maxent(stackmini, p=train_pEOR, a=train_bEOR)
          meHerb <- maxent(stackmini, p=train_pHerb, a=train_bHerb)
          
          #evalidate teh model
          e <- dismo::evaluate(test_pEOR, test_bEOR, me, stackmini)
          eHerb <- dismo::evaluate(test_pHerb, test_bHerb, meHerb, stackmini)
          gc()
          
          #Visulatize predictions
          writeRaster(dismo::predict(me, stackmini),paste("Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/RMaxEnt/EOR",g1g2names$AcceptedName[i],l,".tif", sep=""),overwrite=TRUE)
          gc()
          writeRaster(dismo::predict(meHerb, stackmini),paste("Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/RMaxEnt/Herb",g1g2names$AcceptedName[i],l,".tif", sep=""),overwrite=TRUE)
          gc()
          thres <- dismo::threshold(e) 
          thresHerb <- dismo::threshold(eHerb)
          # 1: which group to withhold, 2: maxent for EOR, 3: maxent for Herbarium, 4: evaluate EOR, 5: evaluate Herbarium, 6: thresholds for EOR, 7: thresholds for Herbarium, 8: species
          out[[l]] <- list(test,me,meHerb,e,eHerb,thres,thresHerb,g1g2names$AcceptedName[i])#,pme,pmeHerb)
          gc()
      }
      out
  }
})
save(Maxentspecies, file= "Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/Data/Maxentspecies.Rda")


```