---
title: "SDM Overlap"
author: "Michelle DePrenger-Levin"
date: "October 17, 2018"
output: html_document
---

```{r}
library(raster)
library(Rmisc)
library(rgdal)
library(ggplot2)

load("Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/Data/g1g2names.Rda")
load("Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/Data/distXsp1.Rda")
colocounties <- readOGR(dsn="Q:/Research/All_Projects_by_Species/aa_Shapefiles_Maps/aa_GENERAL_non-species_files/All_General_Background_Layers/Colorado/CO_Counties", layer="counties_wgs84")
load("Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/Data/g1g2names.Rda")
g1g2names$Family[g1g2names$Family==""] <- "Asteraceae"
g1g2names$Family[g1g2names$Family=="Compositae"] <- "Asteraceae"
g1g2names$Family[g1g2names$Family=="Leguminosae"] <- "Fabaceae"
g1g2names$AcceptedName <- paste(g1g2names$New.Genus,g1g2names$New.Species)

distXsp1 <- mapply('[[', distXsp, 1)
distXsp1 <- do.call(rbind,distXsp1[!is.na(distXsp1)])
want <- which(!is.na(mapply('[[', distXsp, 1)))


```

Just testing
```{r}
testin <-  raster(paste("Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/RMaxEnt/MeanRasterstackEOR",gsub(" ","_","Penstemon degeneri"),"1.tif", sep=""))
#The average is an average, no long bin, need to convert
testin[testin>0.5] <- 1
testin[testin<=0.5] <- 0

plot(testin)

```

```{r}


#really only have 20 species 
sp20 <- g1g2names$AcceptedName[c(1,2,7,10,11,12,16,19,21,22,24,27,35,36,38,41,42,43,45,46)]

Herbrasters <- lapply(sp20, function(sp){
  eorin <- raster(paste("Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/RMaxEnt/MeanRasterstackEOR",gsub(" ","_",sp),"1.tif", sep=""))
  herbin <- raster(paste("Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/RMaxEnt/MeanRasterstackHerb",gsub(" ","_",sp),"1.tif", sep=""))
  
  #Where there is overlap between AsMiEormatchss and AsMi assign a 2 instead of 1 to AsMiEormatchss
  herbin[herbin>0.5] <- 1
  herbin[herbin<=0.5] <- 0
  
  #to see overlap (3) and differentiate from only EOR (2), only herb (1) 
  eorin[eorin>0.5] <- 2
  eorin[eorin<=0.5] <- 0
  
  out <- herbin+eorin
  #Overlap
  overlap <- out
  overlap[overlap!=3] <- NA
  overlapsum <- cellStats(overlap, stat='sum', na.rm=TRUE)
  eoronly <- out
  eoronly[eoronly!=2] <-NA
  eoronlysum <- cellStats(eoronly, stat='sum', na.rm=TRUE)
  herbonly <- out
  herbonly[herbonly!=1] <- NA
  herbonlysum <- cellStats(herbonly, stat='sum', na.rm=TRUE)
  
  outdf <- data.frame(Overlap=overlapsum, EORonly=eoronlysum, Herbonly=herbonlysum)
  outdf
})



```

```{r}
eors <- list()
herbs <- list()
for(sp in 1:length(sp20)){
  eors[[sp]] <- raster(paste("Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/RMaxEnt/MeanRasterstackEOR",gsub(" ","_",sp20[sp]),"1.tif", sep=""))
  herbs[[sp]] <- raster(paste("Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/RMaxEnt/MeanRasterstackHerb",gsub(" ","_",sp20[sp]),"1.tif", sep=""))
}
z
lapply(sp20, function(x){
  eorin <- raster(paste("Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/RMaxEnt/MeanRasterstackEOR",gsub(" ","_",x),"1.tif", sep=""))
  herbin <- raster(paste("Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/RMaxEnt/MeanRasterstackHerb",gsub(" ","_",x),"1.tif", sep=""))
  
  #Where there is overlap between AsMiEormatchss and AsMi assign a 2 instead of 1 to AsMiEormatchss
  herbin[herbin>0.5] <- 1
  herbin[herbin<=0.5] <- 0
  #to see overlap (3) and differentiate from only EOR (2), only herb (1) 
  eorin[eorin>0.5] <- 2
  eorin[eorin<=0.5] <- 0
  out <- herbin+eorin
  
  jpeg(paste("Q:/Research/Projects/alpine-phenology/Uncertainty in niche modeling/Images/Map_",x,".jpg", sep=""),
     width=250, height=225,units='mm', res=300)
     
     plot(out, main=x, xlim=c(-109.5,-101),ylim=c(37,41),col=c("white","#900090","#00a0a0","#707030"))
     plot(colocounties, add=TRUE)
     
     dev.off()

})
  



```


```{r}
overlapall <- do.call(rbind, Herbrasters)
overlapall$totalarea <- rowSums(overlapall)
overlapall$Species <- sp20

#Want to add a distance average and SD and total area for each species
specnum <- as.data.frame(table(distXsp1$SpeciesID,distXsp1$scientificName))
overlapall <- merge(overlapall, specnum[specnum$Freq>0,], by.x = "Species", by.y = "Var2")
distXsp1[distXsp1$scientificName %in% sp20,]@data

summarydistXsp1 <- Rmisc::summarySE(data=distXsp1@data, measurevar = "dist", groupvars = c("SpeciesID"), na.rm=TRUE)
summaryareaXsp1 <- Rmisc::summarySE(data=distXsp1@data, measurevar = "area", groupvars = c("SpeciesID"), na.rm=TRUE)

overlapall <- merge(overlapall, summarydistXsp1, by.x = "Var1", by.y = "SpeciesID")
overlapall <- merge(overlapall, summaryareaXsp1, by.x = "Var1", by.y = "SpeciesID")
overlapall$proporOverlap <- overlapall$Overlap/overlapall$totalarea
overlapall$propHerb <- overlapall$Herbonly/overlapall$totalarea
overlapall$propEOR <- overlapall$EORonly/overlapall$totalarea
overlapall <- merge(overlapall, g1g2names[,-which(names(g1g2names) %in% c("Species"))], by.x="Species", by.y="AcceptedName")

overlapall
```



```{r}
boxplot(overlapall$propHerb, 1,1, border=c("black","white","white"))
boxplot(1, overlapall$propEOR,1, border=c("white","black","white"), add=T)
boxplot(1, 1, overlapall$proporOverlap, border=c("white","white","black"), add=T)
stripchart(list(overlapall$propHerb, overlapall$propEOR,overlapall$proporOverlap), 
                pch=1, method="jitter", vertical = TRUE, 
           col=rep(as.numeric(as.factor(overlapall$Species)),3),add=TRUE)



```


```{r}
library(reshape2)
overlapmelt <- reshape2::melt(overlapall)

anovatest <- overlapmelt[overlapmelt$variable %in% unique(grep(paste(c("over","only"),collapse="|"),
                   overlapmelt$variable, value=TRUE)),]

proptest <- overlapmelt[grep("prop", overlapmelt$variable),]

summary(glm(value~variable, data=proptest))
summary(glm(value~variable, data=anovatest))

ggplot(proptest, aes(variable, value))+
  geom_boxplot()+
  geom_jitter(position=position_jitter(0.2), aes(colour=Family))

table(overlapall$Family)

ggplot(overlapmelt[grep("prop",overlapmelt$variable),], aes(variable, value))+
  geom_boxplot()+
  theme_bw() + 
  geom_jitter(position=position_jitter(0.2), aes(colour=Species))
              

ggplot(overlapmelt[grep("only",overlapmelt$variable),], aes(variable, value))+
  geom_boxplot()+
  theme_bw() + 
  geom_jitter(position=position_jitter(0.2), aes(colour=Species))
              
    
ggplot(overlapall, aes(dist,propHerb))+
  theme_bw() + 
  geom_point(aes(colour=Species))+
  stat_smooth(method="lm")


ggplot(overlapall, aes(area/(1000^2),propHerb))+
  theme_bw() + 
  geom_point(aes(colour=Species))+
  stat_smooth(method="lm")+
  xlab("Square km")

summary(lm(propHerb~area, data=overlapall))

```




